name: "@name@"
version: "@version@"
author: "Siro_256 @ffffff_256"
main: "dev.siro256.spigotpl.floatingguide.FloatingGuide"
api-version: "1.17"

commands:
  test:
    description: "Test command."
    permission: fg.command.test
  wand:
    description: "Give you a wand."
    permission: fg.command.wand

permissions:
  fg.*:
    description: "Permission of all."
    default: op
    children:
      - fg.command.*
  fg.command.*:
    description: "Permission of all commands."
    default: op
    children:
      - fg.command.test
      - fg.command.wand
  fg.command.test:
    description: "Permission of test command."
    default: op
  fg.command.wand:
    description: "Permission of wand command."
    default: op
